services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration:
    build: .
    env_file: .env
    command: 
        bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes: 
        - .:/app
    depends_on: 
          - db

  web:
        build: . 
        env_file: 
        command: #(7)
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn -c gunicorn.conf.py medboard.wsgi:application'
        volumes: 
            - .:/app
        stdin_open: true 
        tty: true 
        ports: 
            - 8000:8000

        depends_on: 
            - db
            - migration
