# Generated by Django 4.1.5 on 2023-01-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="patient",
        ),
    ]
