# Generated by Django 4.1.5 on 2023-01-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "type_of_assistance",
                    models.CharField(
                        choices=[
                            ("Geral", "Geral"),
                            ("Especializada", "Especializada"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type_of_hospital",
                    models.CharField(
                        choices=[("Privado", "Privado"), ("Publico", "Publico")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "financial_goal",
                    models.CharField(
                        choices=[
                            ("Não lucrativo", "Não lucrativo"),
                            ("Filantrópico", "Filantrópico"),
                            ("Beneficente", "Beneficente"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
    ]
)
    ]